# Generated by Django 2.2.7 on 2019-11-09 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzapp', '0002_auto_20191109_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzs', to=settings.AUTH_USER_MODEL),
        ),
    ]
