# Generated by Django 2.2.7 on 2019-11-10 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzapp', '0003_auto_20191109_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='omar-sy-by-rachel.jpg', upload_to='profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statut',
            field=models.BooleanField(default=True),
        ),
    ]
