# Generated by Django 2.2.7 on 2019-11-15 23:39

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzapp', '0004_auto_20191110_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='qpv',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='titre',
        ),
        migrations.AddField(
            model_name='question',
            name='contenu',
            field=tinymce.models.HTMLField(default='def', verbose_name='question_contenu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizz',
            name='pourcentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='pourcentage pour valider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reponse',
            name='contenu',
            field=tinymce.models.HTMLField(default='def', verbose_name='reponse_contenu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='statut',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='statut',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quizzuser',
            name='note',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='quizzuser',
            name='statut',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='statut',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reponseuser',
            name='statut',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='specialisation',
            name='statut',
            field=models.BooleanField(default=True),
        ),
    ]
