# Generated by Django 2.2.7 on 2019-11-15 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzapp', '0005_auto_20191115_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='titre',
        ),
    ]
