# Generated by Django 2.2.7 on 2019-11-15 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzapp', '0006_remove_question_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzuser',
            name='note',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='isrtue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reponseuser',
            name='istrue',
            field=models.BooleanField(default=False),
        ),
    ]
